title: International School on Algorand Smart Contracts
description: Online, September 27 - October 18, 2022
plugins:
  - jekyll-relative-links
relative-links:
  enabled: true
  collections: true
include:
  - README.md
  
